language: node_js

env:
  - CXX=g++-4.8

before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0

before_script:
  - sh -e /etc/init.d/xvfb start

after_success: 'npm run coverage'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  yarn: true
  directories:
    - node_modules
